In [ ]:
quadrado = []

for i in range(0, 10):
    quadrado.append(i ** 2)
    
print(quadrado)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [4]:
quadrado = [i ** 2 for i in range(0, 10)]

print(quadrado)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


# Exercícios Numpy

In [2]:
import numpy as np


In [4]:
# Cria o primeiro array com 8 elementos, todos com o valor 1
array1 = np.ones(8, dtype=int)

# Lê a entrada do usuário e cria o segundo array
numeros_str = input().split()
array2 = np.array([int(x) for x in numeros_str])

# Soma os dois arrays e armazena o resultado em um terceiro array
array_soma = array1 + array2

# Calcula a soma de todos os elementos do array resultante
soma_total = np.sum(array_soma)

# Remodela o array resultante com base na soma total
if soma_total >= 40:
    matriz_resultante = array_soma.reshape(4, 2)
else:
    matriz_resultante = array_soma.reshape(2, 4)

# Imprime os resultados conforme o formato desejado
print("Array resultante da soma:")
print(array_soma)
print("Soma de todos os elementos:")
print(soma_total)

if soma_total >= 40:
    print("Matriz (4 x 2):")
else:
    print("Matriz (2 x 4):")
    
print(matriz_resultante)

Array resultante da soma:
[6 3 1 4 5 2 8 7]
Soma de todos os elementos:
36
Matriz (2 x 4):
[[6 3 1 4]
 [5 2 8 7]]


In [ ]:
numero = input().split() #le o input e cria uma lista de strings

#cria os dois arrays
array_01 = np.array([int(x) for x in numero[0:2]])
array_02 = np.array([int(x) for x in numero[2:4]])

inicio1, fim1 = array_01.min(), array_01.max()
inicio2, fim2 = array_02.min(), array_02.max()

# Cria arrays de pares usando range
array1 = np.array([x for x in range(inicio1, fim1 + 1) if x % 2 == 0]) #a lista só recebe os números que forem pares
array2 = np.array([x for x in range(inicio2, fim2 + 1) if x % 2 == 0]) #a lista só recebe os números que forem pares

# Concatena e ordena
resultado = np.sort(np.concatenate((array1, array2)))

print(resultado)

[2 4 6 8]


In [4]:
array = np.zeros((2, 2), dtype=int)  # Cria uma matriz 2x2 de zeros

numero = input().split()  # Lê a entrada do usuário e cria uma lista de strings 

linha, coluna = int(numero[0]), int(numero[1])  # Converte os dois primeiros elementos para inteiros

array[linha, coluna] = 1  # Define o elemento na posição (linha, coluna) como 1

game_over = False  # Variável para controlar o loop

for i in range(3):  # Itera sobre as linhas
    numero_array = input().split()  # Lê a entrada do usuário e cria uma lista de strings 
    linha_array, coluna_array = int(numero_array[0]), int(numero_array[1])  # Converte os dois primeiros elementos para inteiros
    
    if array[linha_array, coluna_array] == 1:  # Verifica se o elemento na posição (linha_array, coluna_array) é 1
        game_over = True  # Define game_over como True
        break  # Sai do loop
    

if game_over:
    print("Game Over! Try Again!")
else:
    print("Congratulations! You beat the game!")

Congratulations! You beat the game!


In [20]:
import numpy as np

# Lê o número de linhas
numero_linhas = int(input())

matriz = []

for _ in range(numero_linhas):
    #map aplica a função int a cada elemento da lista retornada por input().split()
    linha = list(map(int, input().split()))  # converte cada linha em lista de inteiros
    matriz.append(linha)

# transforma em numpy array
array_total = np.array(matriz)

# obtém formato da matriz
linhas, colunas = array_total.shape #é como se fosse linhas = array_total.shape[0] e colunas = array_total.shape[1]
#obs: se eu colocar mais uma variável, vai dar erro, porque as duas variáveis estão capturando em sequência os valores da tupla retornada por shape

print(f"{linhas} linhas")
print(f"{colunas} colunas")

# calcula total de elementos
total_elementos = linhas * colunas

# verifica se é par ou ímpar
if total_elementos % 2 == 0:
    print("O vetor resultante teria um número par de elementos.")
else:
    print("O vetor resultante teria um número ímpar de elementos.")


2 linhas
3 colunas
O vetor resultante teria um número par de elementos.


In [8]:
import numpy as np

numero_seed = int(input()) #número para a seed
seed = np.random.seed(numero_seed) #define a seed para números aleatórios

#gera números aleatórios entre 1 e 50
numeros = np.random.randint(1, 51, size=(4,4)) #gera uma matriz 4x4 com números aleatórios entre 1 e 50


#média de linhas
media_linhas = np.mean(numeros, axis=1) #calcula a média de cada linha
print(f"Média das linhas: {media_linhas}")

#média de colunas
media_colunas = np.mean(numeros, axis=0) #calcula a média de cada coluna
print(f"Média das colunas: {media_colunas}")

#maior média das linhas
maior_media_linhas = np.max(media_linhas) #encontra a maior média entre as linhas
print(f"Maior média das linhas: {maior_media_linhas}")

#maior média das colunas
maior_media_colunas = np.max(media_colunas) #encontra a maior média entre as colunas
print(f"Maior média das colunas: {maior_media_colunas}")

#valores e frequência de cada número da matriz
valores, frequencia = np.unique(numeros, return_counts=True) #retorna os valores únicos e suas frequências
print(f"Valores: {valores}")
print(f"Contagens: {frequencia}")  


#números que aparecem 2 vezes
#retrona uma lista de tuplas (num, freq) e filtra os que têm freq == 2
#num e freq são variáveis temporárias que recebem os valores das tuplas durante a iteração
#o primeiro num vai receber o primeiro valor da tupla referente a tupla que passou pelo filtro
frequencia_dict = dict(zip(valores, frequencia)) #cria um dicionário com os valores e suas frequências
numeros_duas_vezes = [num for num, freq in frequencia_dict.items() if freq == 2] #filtra os números que aparecem exatamente 2 vezes
print(f"Números que aparecem 2 vezes: {numeros_duas_vezes}")

Média das linhas: [16.   33.75 34.5  23.75]
Média das colunas: [29.75 24.25 33.75 20.25]
Maior média das linhas: 34.5
Maior média das colunas: 33.75
Valores: [ 1  9 10 16 26 29 30 37 41 43 49 50]
Contagens: [2 1 2 1 1 1 2 1 1 1 1 2]
Números que aparecem 2 vezes: [np.int32(1), np.int32(10), np.int32(30), np.int32(50)]
